"""Artistic prompt collection - creative styles and abstract concepts.

First artistic collection featuring artistic movements, abstract visualizations,
and creative styles.
"""

ARTISTIC_PROMPTS = {
    "impressionist_dreams": [
        "water lilies pond, monet style, soft brushstrokes, pastel colors, dreamy atmosphere",
        "parisian cafe terrace at night, warm glowing lights, loose brushwork, impressionist",
        "hay stacks at different times of day, golden light, impressionist landscape",
        "ballet dancers backstage, degas style, soft pastels, movement captured",
        "river seine with boat reflections, renoir inspired, dappled light, romantic",
        "garden party in summer, parasols and dresses, impressionist technique",
        "wheat field with poppies, vibrant reds and golds, textured brushstrokes",
        "bridge over pond, japanese influence, atmospheric perspective, impressionist",
    ],
    "abstract_expressionism": [
        "color field explosion, rothko inspired, layers of emotion, bold rectangles",
        "action painting, pollock style, energetic drips and splatters, controlled chaos",
        "geometric abstraction, mondrian influence, primary colors, black lines",
        "abstract landscape suggestion, kandinsky style, musical composition in color",
        "biomorphic forms floating, miro inspired, playful abstract shapes",
        "color blocks in tension, malevich suprematism, pure geometric feeling",
        "gestural brushstrokes, de kooning energy, aggressive yet graceful marks",
        "meditative color gradients, newman style, vertical zips, contemplative",
    ],
    "surrealist_visions": [
        "persistence of time, soft watches draped, desert landscape, dali inspired",
        "floating green apple obscuring face, magritte mystery, suit and bowler hat",
        "elephant with spider legs, fragile yet massive, surreal contradiction",
        "keyhole revealing eye, looking through layers, voyeuristic surrealism",
        "chess pieces on infinite board, strategy and futility, metaphysical",
        "double image optical illusion, two scenes in one, perceptual puzzle",
        "burning giraffe, freudian symbolism, war and destruction, surreal nightmare",
        "lovers with cloth-covered faces, intimacy and anonymity, romantic mystery",
    ],
    "cubist_deconstruction": [
        "portrait from multiple angles simultaneously, picasso inspired, fractured planes",
        "guitar and bottle on table, braque style, muted colors, overlapping shapes",
        "cityscape fragmented into geometric forms, sharp angles, analytical cubism",
        "still life with newspaper, collage elements, synthetic cubism technique",
        "violin deconstructed, musical instrument as abstract form, multiple perspectives",
        "figure descending staircase, motion through cubist lens, duchamp influence",
        "three musicians, flat colored shapes, synthetic cubism, rhythmic composition",
        "african mask influence, primitive and modern merged, cubist portrait",
    ],
    "art_nouveau_elegance": [
        "flowing hair becoming floral vines, mucha style, decorative border, organic",
        "peacock feather patterns, iridescent colors, art nouveau curves",
        "woman in flowing dress, botanical elements, poster design, ornamental",
        "stained glass with nature motifs, lead lines, jewel tones, architectural art nouveau",
        "dragonfly wing details, geometric yet organic, jewelry design aesthetic",
        "whiplash curves and tendrils, klimt gold influence, decorative patterns",
        "four seasons personified, allegorical figures, art nouveau symbolism",
        "iris flowers stylized, purple and green harmony, poster art elegance",
    ],
    "pop_art_bold": [
        "comic book explosion, roy lichtenstein dots, bold outlines, primary colors",
        "soup can array, warhol repetition, consumer culture commentary",
        "celebrity portrait screen print, vibrant contrasts, iconic pop imagery",
        "collage of magazine cutouts, david hockney pool, californian bright",
        "comic speech bubble, 'wow!', benday dots, graphic novel aesthetic",
        "enlarged everyday object, claes oldenburg scale, mundane made monumental",
        "british flag color palette, peter blake collage, nostalgic assemblage",
        "halftone portrait, multiple color variations, repetition and variation",
    ],
    "minimalist_zen": [
        "single line drawing, continuous contour, elegant simplicity, less is more",
        "three stones stacked, perfect balance, negative space, meditative",
        "square within square, albers homage, subtle color relationships",
        "empty white canvas with tiny dot, contemplation of nothing and everything",
        "parallel lines in space, repetition and rhythm, optical subtlety",
        "monochrome gradient, smooth transition, atmospheric minimalism",
        "grid system, sol lewitt mathematical, conceptual minimalism",
        "light and shadow only, no objects, architectural minimalism, pure form",
    ],
    "street_art_urban": [
        "colorful graffiti mural, hip hop culture, spray paint texture, urban energy",
        "banksy style political stencil, ironic message, guerrilla art",
        "yarn bombing tree, knitted street art, colorful textile installation",
        "wheatpaste poster layers, weathered urban texture, contemporary folk art",
        "3d anamorphic street painting, optical illusion on pavement, interactive",
        "mosaic portrait from tiles, invader pixel art, video game aesthetic",
        "stencil portrait layers, multiple colors, street art technique",
        "calligraffiti fusion, arabic script meets graffiti, cultural blend",
    ],
    "digital_glitch_art": [
        "pixel sorting cascade, data moshing, corrupted image beauty",
        "rgb color channel separation, chromatic aberration, glitch aesthetic",
        "broken jpeg artifacts, compression errors as art, digital decay",
        "datamosh face portrait, temporal distortion, video glitch frozen",
        "ascii art portrait, text characters forming image, retro computer",
        "circuit bent colors, hardware malfunction aesthetic, beautiful errors",
        "vhs tracking errors, analog glitch, nostalgic distortion",
        "database corruption visualization, numbers becoming abstract art",
    ],
    "watercolor_fluidity": [
        "loose floral bouquet, wet-on-wet technique, colors bleeding beautifully",
        "misty mountain landscape, atmospheric watercolor, soft edges, ethereal",
        "abstract wash layers, transparent overlaps, organic color mixing",
        "portrait with dripping colors, emotional watercolor, expressive looseness",
        "ocean waves, fluid motion captured, turquoise washes, coastal scene",
        "autumn trees, warm washes, negative space, leaves suggested not detailed",
        "rainy city street, reflections and atmosphere, moody watercolor",
        "koi pond from above, fish in water, depth through transparency",
    ],
    "art_deco_geometry": [
        "chrysler building spire, stepped geometric forms, metallic art deco",
        "jazz age poster, geometric figures dancing, gold and black elegance",
        "sunburst pattern radiating, symmetrical art deco motif, streamline moderne",
        "egyptian revival design, geometric hieroglyphs, 1920s glamour",
        "ziggurat stepped pyramid, art deco architecture, bold angular forms",
        "stylized gazelle leaping, art deco animal, elegant linear forms",
        "fan pattern ceiling, geometric luxury, art deco interior detail",
        "speed lines and chrome, machine age aesthetic, streamlined forms",
    ],
    "psychedelic_experience": [
        "concentric rainbow circles expanding, optical vibration, trippy patterns",
        "paisley swirls and fractals, 1960s poster art, mind-expanding visuals",
        "melting face morphing, liquid reality, psychedelic transformation",
        "kaleidoscope mandala, infinite symmetry, meditation visual",
        "warping checkerboard floor, perspective distortion, reality bending",
        "fluorescent colors under blacklight, day-glo intensity, rave aesthetic",
        "eye with spiral pupil, hypnotic gaze, consciousness visualization",
        "mushroom forest glowing, alice in wonderland trip, magical realism",
    ],
    "chiaroscuro_drama": [
        "single candle illuminating face, caravaggio lighting, dramatic shadows",
        "fruits on table, renaissance still life, raking light, dutch master style",
        "figure emerging from darkness, rembrandt technique, spotlight effect",
        "hands in prayer, tenebrism, spiritual light from above, baroque drama",
        "musician in shadow playing instrument, vermeer light quality, intimate",
        "elderly person reading by window, soft directional light, contemplative",
        "wine glass and bread, last supper lighting, symbolic still life",
        "self portrait half in shadow, psychological depth, dramatic contrast",
    ],
    "collage_assemblage": [
        "vintage magazine cutouts layered, retro mixed media, nostalgic compilation",
        "found objects arranged, joseph cornell box, shadow box art",
        "torn paper pieces, abstract composition, textured layers",
        "photographs and text combined, dada influence, nonsense poetry",
        "fabric swatches quilted, textile collage, pattern on pattern",
        "botanical specimens pressed, scientific meets artistic, herbarium art",
        "ticket stubs and ephemera, memory collage, time capsule aesthetic",
        "maps torn and layered, geographical abstraction, journey compilation",
    ],
    "ink_illustration": [
        "detailed pen and ink cityscape, crosshatching technique, architectural drawing",
        "botanical illustration, scientific accuracy, stippling texture",
        "portrait with fine lines, engraving style, classical technique",
        "japanese sumi-e bamboo, minimal brush strokes, zen simplicity",
        "comic book noir scene, heavy blacks, dramatic ink work",
        "calligraphy forming image, letterforms as art, typographic illustration",
        "woodcut print aesthetic, bold black and white, folk art simplicity",
        "ink wash landscape, chinese mountain painting, misty atmospheric",
    ],
    "fauvism_wild_color": [
        "landscape in unnatural colors, matisse inspired, decorative flatness",
        "portrait with green face, fauvist palette, emotional color choice",
        "harbor with boats, bright unrealistic hues, wild colorist approach",
        "interior with red room, pattern overload, fauvist decoration",
        "trees in purple and orange, liberated color, expressive not realistic",
        "still life with impossible colors, emotional temperature through hue",
        "dancers in vivid non-local color, movement through fauvism",
        "window view with clashing colors, matisse cutout influence",
    ],
    "gothic_romanticism": [
        "ruined abbey under moonlight, caspar david friedrich, sublime nature",
        "lone figure on mountain peak, romantic contemplation, infinite landscape",
        "shipwreck in storm, turner drama, nature's overwhelming power",
        "cemetery with weeping angels, gothic melancholy, marble and ivy",
        "haunted castle on cliff, dark romanticism, mysterious atmosphere",
        "ancient oak tree, gnarled and twisted, romantic symbolism",
        "fog rolling over moors, bronte landscape, lonely and beautiful",
        "medieval cathedral interior, gothic arches, spiritual light",
    ],
    "pointillism_dots": [
        "sunday afternoon park scene, seurat style, countless tiny dots",
        "circus performance, signac technique, optical color mixing",
        "harbor at sunset, pointillist dots creating luminous water",
        "portrait built from colored points, divisionism technique",
        "eiffel tower through trees, neo-impressionist dots, parisian view",
        "dancers in dotted light, chromoluminarism, vibrant optical mixing",
        "beach scene with parasols, summer light through pointillism",
        "garden path, dot by dot creation, patient technique, luminous result",
    ],
    "bauhaus_functional": [
        "geometric furniture design, form follows function, primary colors",
        "typography poster, sans serif boldness, bauhaus grid system",
        "architectural blueprint aesthetic, clean lines, modernist vision",
        "abstract shapes teaching color theory, itten influence, systematic",
        "steel tube chair, marcel breuer style, industrial materials as art",
        "workshop tools arranged, function as beauty, honest materials",
        "modular design system, repeating elements, bauhaus efficiency",
        "light and shadow study, moholy-nagy photogram, experimental",
    ],
    "magical_realism": [
        "woman with butterflies emerging from book, reality with magic touch",
        "house floating on cloud, dreamlike yet painted realistically",
        "tree growing books as leaves, literacy metaphor, surreal but detailed",
        "hourglass containing miniature seasons changing, time visualization",
        "umbrella raining upward, impossibility rendered realistically",
        "staircase leading underwater seamlessly, two worlds merged naturally",
        "girl with galaxy hair, cosmos in portrait, magical yet grounded",
        "violin releasing birds as music, synesthesia visualized, poetic realism",
    ],
}
