"""Ultimate prompt collection - comprehensive diverse prompts.

The most comprehensive collection of prompt categories and themes,
combining and expanding upon all previous generation scripts.
"""

ULTIMATE_PROMPTS = {
    "cosmic_wonders": [
        "spiral galaxy with vibrant nebula, deep space photography, cosmic dust clouds, 4k astronomy",
        "black hole event horizon, warped spacetime, glowing accretion disk, scientific visualization",
        "twin binary stars orbiting, stellar corona, solar flares, space telescope image",
        "supernova explosion, shockwave expanding, cosmic debris, colorful gas clouds",
        "alien exoplanet with three moons, gas giant rings, purple atmosphere, sci-fi realism",
        "asteroid belt, rocky debris field, distant sun, epic space vista, cinematic",
        "pulsar neutron star, magnetic field lines, high energy beams, scientific art",
        "planetary nebula, dying star, colorful expanding shells, deep field image",
    ],
    "mythological_beings": [
        "phoenix rising from golden flames, glowing embers, mythical firebird, epic wings spread",
        "ancient dragon perched on castle ruins, detailed scales, moonlit night, fantasy epic",
        "mermaid queen in bioluminescent ocean depths, coral throne, ethereal underwater beauty",
        "majestic unicorn in enchanted forest, magical sparkles, moonbeams filtering through trees",
        "thunderbird summoning storm, lightning crackling, native american mythology, powerful",
        "kraken emerging from stormy seas, massive tentacles, sailing ship, dramatic waves",
        "griffin guardian of ancient temple, lion and eagle hybrid, golden hour light",
        "basilisk serpent with crown, poisonous gaze, dark cavern, mythical monster art",
    ],
    "retro_aesthetics": [
        "1980s neon cityscape, retrowave sunset, palm trees silhouette, vaporwave pink and purple",
        "vintage arcade cabinet glowing, pixel art game, dim room, nostalgic 80s atmosphere",
        "1950s american diner, chrome fixtures, checkered floor, jukebox playing, classic cars outside",
        "retro cassette tape, tangled magnetic film, macro closeup, 80s music nostalgia",
        "old polaroid camera, instant photos scattered, vintage aesthetic, warm analog feel",
        "neon signs reflecting in rain puddles, blade runner style, cyberpunk retro, night city",
        "vintage transistor radio, wood paneling, glowing dial, 1970s living room",
        "classic jukebox with vinyl records, colorful lights, 1960s soda shop interior",
    ],
    "surreal_dreams": [
        "melting clocks draped over twisted trees, salvador dali inspired, dreamscape reality",
        "floating islands connected by impossible waterfalls, clouds below, surreal physics",
        "single door standing in vast desert, no walls, mysterious portal, minimalist surrealism",
        "giant teacup containing miniature city, tiny people, whimsical alice wonderland style",
        "infinite staircase spiraling in clouds, MC escher impossible geometry, mind-bending",
        "man in bowler hat with apple obscuring face, magritte surrealism, mysterious portrait",
        "bedroom ceiling covered with ocean waves, underwater room, reality inversion",
        "tree growing upside down from sky, roots in clouds, leaves underground, paradox",
    ],
    "four_seasons": [
        "autumn forest path, carpet of red and gold leaves, misty morning, peaceful serenity",
        "spring cherry blossom tunnel, pink petals falling like snow, soft romantic light",
        "winter wonderland, frozen waterfall, icicles, snow-covered evergreens, blue hour magic",
        "summer sunflower field at golden hour, warm sunset glow, pastoral landscape",
        "fall harvest scene, pumpkin patch, hay bales, orange autumn sky, rustic farm",
        "spring rain shower, fresh flowers blooming, raindrops on petals, renewal and growth",
        "winter northern lights, snow-covered log cabin, aurora borealis dancing, starry night",
        "summer beach at sunrise, pastel sky, calm turquoise water, peaceful morning meditation",
    ],
    "portrait_characters": [
        "wise elderly wizard reading ancient spellbook, candlelight, long white beard, magical study",
        "cyberpunk hacker with neon tattoos, city lights reflected in eyes, rain, futuristic",
        "steampunk inventor with brass goggles, workshop full of gears, victorian aesthetic",
        "tribal warrior with ceremonial paint, fierce expression, cultural photography, powerful",
        "ballerina mid-leap in flowing white dress, stage lights, graceful frozen motion",
        "astronaut portrait, earth reflection in helmet visor, stars, heroic space explorer",
        "geisha in traditional kimono, kyoto streets, cherry blossoms, cultural elegance",
        "viking shield maiden with braided hair, war paint, fierce nordic warrior, dramatic",
    ],
    "macro_mysteries": [
        "dewdrop on spider web at sunrise, backlit golden light, macro detail, nature close-up",
        "butterfly wing scales extreme macro, iridescent colors, scientific photography",
        "snowflake crystal structure on dark wool, geometric patterns, winter macro beauty",
        "soap bubble surface, rainbow swirls, macro abstract, delicate transparent sphere",
        "bee covered in yellow pollen, flower stamens, macro wildlife, pollination moment",
        "watch mechanism gears, intricate clockwork, steampunk macro, mechanical precision",
        "peacock feather eye, microscopic detail, vibrant blues and greens, natural art",
        "salt crystals forming patterns, macro closeup, geometric mineral structures, abstract",
    ],
    "minimalist_zen": [
        "single red balloon floating against clear blue sky, minimalist composition, simple joy",
        "solitary tree on rolling green hill, negative space, fog, zen landscape meditation",
        "geometric bauhaus shapes, primary colors, flat design, modern minimalist art",
        "zen garden sand ripples, three stones, minimalist japanese aesthetic, peaceful",
        "single feather falling through white space, minimal still life, delicate grace",
        "lone boat on calm lake, mirror reflection, pastel dawn, serene minimalism",
        "abstract color field, rothko inspired, soft edge rectangles, contemplative art",
        "single leaf floating on water, concentric ripples, zen moment, natural minimalism",
    ],
    "culinary_art": [
        "gourmet chocolate dessert, gold leaf decoration, artistic plating, fine dining photography",
        "colorful macarons arranged on marble, pastel rainbow, french patisserie, overhead shot",
        "steaming ramen bowl, chopsticks, soft-boiled egg, japanese cuisine, cozy atmosphere",
        "fresh berries in antique bowl, rustic wooden table, natural window light, farm fresh",
        "artisan sourdough bread, crust detail, steam rising, bakery atmosphere, warm light",
        "sushi chef crafting nigiri, precision cutting, fresh fish, culinary art performance",
        "italian pasta making, flour dust, hands kneading dough, rustic kitchen, tradition",
        "coffee latte art, heart foam design, ceramic cup, cafe morning light, inviting",
    ],
    "weather_phenomena": [
        "lightning bolt striking ocean during storm, long exposure, dramatic power of nature",
        "morning fog rolling through mountain valley, layers of hills, moody atmosphere",
        "double rainbow over green countryside, rain clearing, hope and natural beauty",
        "tornado funnel forming in wheat field, ominous dark clouds, storm chaser perspective",
        "sun rays breaking through storm clouds, crepuscular rays, divine light, inspiring",
        "mammatus clouds, unusual formations, severe weather, dramatic sky, natural wonder",
        "ice storm coating trees, crystalline branches, winter wonderland, frozen beauty",
        "dust devil in arizona desert, red rock landscape, swirling sand, wild weather",
    ],
    "architectural_marvels": [
        "futuristic glass skyscraper, reflective facade, blue sky, modern architectural photography",
        "ancient gothic cathedral interior, stained glass windows, divine light rays, sacred space",
        "japanese temple in autumn, red torii gate, maple leaves, traditional architecture",
        "modern minimalist house, concrete and glass, infinity pool, architectural digest style",
        "moroccan palace courtyard, ornate zellige tiles, fountain, arches, warm sunlight",
        "brutalist concrete building, geometric shapes, soviet architecture, dramatic angles",
        "art deco building facade, gold accents, 1920s elegance, miami beach style",
        "bamboo forest temple, zen architecture, natural materials, harmony with nature",
    ],
    "urban_exploration": [
        "tokyo street at night, neon signs reflecting in rain, cyberpunk atmosphere, cinematic",
        "abandoned factory interior, rust and decay, urban exploration, dramatic shafts of light",
        "cobblestone european alley, flower boxes, cafe tables, golden afternoon, romantic",
        "new york city rooftop view, sunset skyline, urban photography, metropolis energy",
        "street art mural, colorful graffiti, urban culture, large scale wall painting",
        "night market in bangkok, food stalls, lanterns, bustling atmosphere, street photography",
        "london fog, big ben clock tower, red telephone booth, moody urban atmosphere",
        "dubai skyline at dusk, illuminated skyscrapers, desert modern, luxury cityscape",
    ],
    "wildlife_moments": [
        "peacock displaying full tail feathers, vibrant iridescent colors, botanical garden",
        "arctic fox in snow, white fur, blue hour lighting, nature documentary style",
        "hummingbird frozen mid-flight, feeding on flower, macro, tropical colors",
        "elephant family at watering hole, golden sunset, african savanna, dramatic silhouette",
        "owl perched on branch, intense eyes, moonlit forest, wildlife portrait",
        "sea turtle swimming in coral reef, underwater, marine life, ocean conservation",
        "red panda in bamboo forest, cute expression, endangered species, natural habitat",
        "cheetah running at full speed, motion blur, hunting, wild africa, powerful grace",
    ],
    "fantasy_landscapes": [
        "crystal cave with glowing minerals, underground lake, magical geodes, fantasy exploration",
        "floating castle in clouds, waterfalls cascading down, epic fantasy architecture",
        "bioluminescent forest at night, glowing mushrooms, magical fairy tale atmosphere",
        "volcanic landscape, lava flows, ash clouds, primordial earth, dramatic geology",
        "ice palace in frozen tundra, aurora overhead, fantasy kingdom, winter magic",
        "giant sequoia forest, ancient trees, mystical fog, cathedral of nature",
        "desert oasis, palm trees, clear spring water, sand dunes, serene refuge",
        "Scottish highlands, misty mountains, castle ruins, heather fields, celtic atmosphere",
    ],
    "sci_fi_futures": [
        "space station interior, holographic displays, futuristic design, sci-fi concept art",
        "cyberpunk street market, neon signs, androids, rain reflections, blade runner aesthetic",
        "mars colony dome, red planet surface, terraforming, future human settlement",
        "steampunk airship, brass machinery, clouds, victorian era fusion, fantasy technology",
        "alien technology, glowing symbols, advanced civilization, mysterious artifacts",
        "post-apocalyptic cityscape, overgrown buildings, nature reclaiming, dramatic sky",
        "underwater city, geodesic domes, submarines, futuristic ocean colonization",
        "robot factory, assembly line, industrial sci-fi, mechanical precision, future industry",
    ],
    "abstract_expressions": [
        "fluid art, swirling marble patterns, gold and turquoise, abstract expressionism",
        "geometric mandala, intricate symmetrical patterns, vibrant gradients, spiritual art",
        "watercolor wash, soft color blending, pastel abstract, dreamy impressionism",
        "fractal mathematics visualization, infinite patterns, psychedelic colors, digital art",
        "jackson pollock style, action painting, splatter technique, abstract energy",
        "color field painting, rothko inspired, contemplative rectangles, emotional depth",
        "kinetic motion blur, light trails, abstract movement, dynamic energy",
        "molecular structure, atoms and bonds, scientific abstract, microscopic beauty",
    ],
    "still_life_classics": [
        "vintage typewriter, old books, coffee cup, wooden desk, writer's atmosphere",
        "fresh fruit bowl, dramatic chiaroscuro lighting, dutch masters style, oil painting aesthetic",
        "origami crane collection, pastel paper, soft shadows, japanese minimalist art",
        "antique pocket watch, gears visible, macro photography, steampunk details",
        "wilting roses in crystal vase, symbolism, memento mori, classical still life",
        "vinyl record player, spinning disc, warm lamp light, music nostalgia, analog",
        "seashell collection on driftwood, beach findings, natural history, coastal aesthetic",
        "vintage perfume bottles, art deco glass, vanity table, feminine elegance, soft focus",
    ],
    "underwater_worlds": [
        "coral reef ecosystem, tropical fish, sunlight filtering through water, marine biodiversity",
        "shipwreck covered in coral, underwater exploration, mysterious depths, diving photography",
        "jellyfish floating in dark water, bioluminescent glow, ethereal sea creatures",
        "dolphins playing in crystal clear ocean, underwater photography, marine mammals",
        "kelp forest, sea otters, underwater jungle, california coast, marine sanctuary",
        "manta ray gliding overhead, underwater perspective, graceful sea creature, ocean giant",
        "sea anemone closeup, clownfish, symbiotic relationship, macro marine life",
        "underwater cave, light shafts penetrating, cenote diving, mysterious blue depths",
    ],
    "cultural_celebrations": [
        "indian holi festival, explosion of color powder, celebration, joyful energy",
        "day of the dead altar, marigolds, sugar skulls, candles, mexican tradition",
        "chinese new year, red lanterns, dragon dance, fireworks, cultural celebration",
        "brazilian carnival, colorful costumes, feathers, samba dancers, festive energy",
        "japanese tea ceremony, matcha preparation, minimalist ritual, cultural meditation",
        "scottish highland games, kilts, bagpipes, athletic competition, celtic tradition",
        "venetian carnival mask, ornate decoration, mysterious elegance, italian tradition",
        "diwali lights, oil lamps, rangoli patterns, indian festival of lights, celebration",
    ],
    "time_of_day": [
        "golden hour meadow, warm sunlight, wildflowers, magic hour photography, peaceful",
        "blue hour cityscape, twilight, lights beginning to glow, transitional beauty",
        "midday harsh shadows, architectural photography, strong contrast, summer heat",
        "dawn breaking over ocean, first light, pastel sky, new beginning, hope",
        "midnight moon, stars visible, long exposure, night sky photography, cosmic",
        "afternoon tea time, soft window light, cozy interior, relaxing moment",
        "dusk silhouettes, sunset colors, dramatic sky, day ending, contemplative",
        "predawn darkness, last stars fading, anticipation of sunrise, quiet moment",
    ],
    "textural_studies": [
        "tree bark macro, detailed texture, natural patterns, organic surface, close-up",
        "rusted metal surface, oxidation patterns, industrial decay, abstract texture",
        "cracked earth, drought patterns, natural geometry, environmental texture",
        "fabric folds, silk material, light and shadow, textile study, elegant draping",
        "weathered wood grain, aged surface, natural wear, rustic texture, time's passage",
        "ice crystals forming patterns, frost on window, winter texture, natural art",
        "sand ripples, wind patterns, desert texture, natural waves, minimalist",
        "brick wall detail, mortar lines, architectural texture, urban surface, geometric",
    ],
    "emotional_atmospheres": [
        "lonely bench in fog, empty park, solitude, melancholy mood, contemplative",
        "joyful child running through sprinkler, summer fun, happiness, candid moment",
        "tense chess game, focused players, competitive atmosphere, intellectual battle",
        "serene meditation, peaceful pose, calm environment, inner peace, mindfulness",
        "anxious storm approaching, dark clouds, ominous atmosphere, tension, dramatic",
        "romantic sunset picnic, couple silhouette, love, intimate moment, warm colors",
        "nostalgic childhood bedroom, vintage toys, memories, sentimental, soft focus",
        "triumphant mountain summit, arms raised, achievement, inspiring, victory pose",
    ],
    "light_and_shadow": [
        "venetian blinds casting striped shadows, noir aesthetic, dramatic contrast, mystery",
        "spotlight on empty stage, dramatic lighting, theater atmosphere, anticipation",
        "stained glass window light patterns on floor, colorful shadows, sacred geometry",
        "forest sunbeams, light rays through trees, atmospheric fog, divine light",
        "silhouette against sunset, backlit figure, dramatic outline, golden hour",
        "chiaroscuro portrait, rembrandt lighting, dramatic shadow, classical technique",
        "long shadow at sunset, extended form, golden hour, artistic photography",
        "paper cutout shadow art, layered shadows, creative lighting, artistic installation",
    ],
    "magical_realism": [
        "books flying around library, magical literacy, whimsical, fantasy atmosphere",
        "garden where flowers bloom instantly, time-lapse effect, magical nature, wonder",
        "mirror reflecting different season, magical portal, reality shift, surreal",
        "stars falling from sky into jar, catching stardust, magical collection, dreamy",
        "painting coming to life, canvas reality blend, magical art, metamorphosis",
        "clock running backwards, time reversal, temporal magic, surreal concept",
        "footprints glowing in darkness, magical trail, bioluminescent path, fantasy night",
        "umbrella holding up rain cloud, whimsical weather, playful magic, cute surrealism",
    ],
}
