"""add_community_gallery_tables

Revision ID: 0e34592e44db
Revises:
Create Date: 2026-02-02 07:33:15.892345

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e34592e44db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creation_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("theme", sa.String(), nullable=True),
        sa.Column("images_created", sa.Integer(), nullable=True),
        sa.Column("images_kept", sa.Integer(), nullable=True),
        sa.Column("avg_score", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generated_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("negative_prompt", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("source_query", sa.String(), nullable=True),
        sa.Column("model_id", sa.String(), nullable=False),
        sa.Column("generation_params", sa.JSON(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("aesthetic_score", sa.Float(), nullable=True),
        sa.Column("clip_score", sa.Float(), nullable=True),
        sa.Column("technical_score", sa.Float(), nullable=True),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("share_id", sa.String(length=12), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("share_count", sa.Integer(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generated_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_images_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_filename"), ["filename"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_final_score"), ["final_score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_is_public"), ["is_public"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_like_count"), ["like_count"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_model_id"), ["model_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_share_id"), ["share_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generated_images_view_count"), ["view_count"], unique=False
        )

    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("model_path", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("dataset_size", sa.Integer(), nullable=True),
        sa.Column("final_loss", sa.Float(), nullable=True),
        sa.Column("training_time_seconds", sa.Float(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gallery_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"], ["generated_images.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("gallery_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_comments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gallery_comments_image_id"), ["image_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gallery_comments_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "gallery_likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"], ["generated_images.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("gallery_likes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_likes_image_id"), ["image_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gallery_likes_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "gallery_shares",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("shared_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"], ["generated_images.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("gallery_shares", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gallery_shares_image_id"), ["image_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gallery_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_shares_image_id"))

    op.drop_table("gallery_shares")
    with op.batch_alter_table("gallery_likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_likes_session_id"))
        batch_op.drop_index(batch_op.f("ix_gallery_likes_image_id"))

    op.drop_table("gallery_likes")
    with op.batch_alter_table("gallery_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gallery_comments_session_id"))
        batch_op.drop_index(batch_op.f("ix_gallery_comments_image_id"))
        batch_op.drop_index(batch_op.f("ix_gallery_comments_created_at"))

    op.drop_table("gallery_comments")
    op.drop_table("training_sessions")
    with op.batch_alter_table("generated_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generated_images_view_count"))
        batch_op.drop_index(batch_op.f("ix_generated_images_status"))
        batch_op.drop_index(batch_op.f("ix_generated_images_share_id"))
        batch_op.drop_index(batch_op.f("ix_generated_images_model_id"))
        batch_op.drop_index(batch_op.f("ix_generated_images_like_count"))
        batch_op.drop_index(batch_op.f("ix_generated_images_is_public"))
        batch_op.drop_index(batch_op.f("ix_generated_images_final_score"))
        batch_op.drop_index(batch_op.f("ix_generated_images_filename"))
        batch_op.drop_index(batch_op.f("ix_generated_images_created_at"))

    op.drop_table("generated_images")
    op.drop_table("creation_sessions")
    # ### end Alembic commands ###
